const fakeAppointments = [
  {
    id: 12,
    user_name: "George Miller",
    title: "QA Testing",
    selectDay: "Wednesday, April 09, 2025",
    selectTime: "10:00 AM",
    slot: 30,
    type: "lineup",
    user_role: "Admin",
  },

  {
    id: 7,
    user_name: "Hannah Moore",
    title: "Weekly Planning",
    selectDay: "Thursday, April 10, 2025",
    selectTime: "10:00 AM",
    slot: 60,
    type: "upcoming",
    user_role: "user",
  },
  {
    id: 8,
    user_name: "Julia Roberts",
    title: "Innovation Workshop",
    selectDay: "Thursday, April 10, 2025",
    selectTime: "11:00 AM",
    slot: 45,
    type: "upcoming",
    user_role: "user",
  },
  {
    id: 9,
    user_name: "Paul Walker",
    title: "Ops Update",
    selectDay: "Thursday, April 10, 2025",
    selectTime: "12:00 PM",
    slot: 30,
    type: "upcoming",
    user_role: "user",
  },

  {
    id: 1,
    user_name: "Alice Johnson",
    title: "Project Kickoff",
    selectDay: "Friday, April 11, 2025",
    selectTime: "10:00 AM",
    slot: 60,
    type: "upcoming",
    user_role: "Admin",
  },
  {
    id: 2,
    user_name: "Bob Smith",
    title: "Design Review",
    selectDay: "Friday, April 11, 2025",
    selectTime: "11:00 AM",
    slot: 45,
    type: "lineup",
    user_role: "user",
  },
  {
    id: 3,
    user_name: "Fiona Davis",
    title: "Strategy Meeting",
    selectDay: "Friday, April 11, 2025",
    selectTime: "12:00 PM",
    slot: 45,
    type: "lineup",
    user_role: "user",
  },

  {
    id: 10,
    user_name: "Dana White",
    title: "Team Retrospective",
    selectDay: "Saturday, April 12, 2025",
    selectTime: "01:00 PM",
    slot: 90,
    type: "lineup",
    user_role: "Admin",
  },
  {
    id: 11,
    user_name: "Nathan Drake",
    title: "UX Brainstorm",
    selectDay: "Saturday, April 12, 2025",
    selectTime: "02:30 PM",
    slot: 60,
    type: "upcoming",
    user_role: "user",
  },

  {
    id: 13,
    user_name: "Ethan Williams",
    title: "Product Demo",
    selectDay: "Sunday, April 13, 2025",
    selectTime: "10:00 AM",
    slot: 30,
    type: "upcoming",
    user_role: "user",
  },
  {
    id: 14,
    user_name: "Queen Latifah",
    title: "Leadership Check",
    selectDay: "Sunday, April 13, 2025",
    selectTime: "11:00 AM",
    slot: 30,
    type: "lineup",
    user_role: "Admin",
  },

  {
    id: 15,
    user_name: "Liam Scott",
    title: "HR Feedback",
    selectDay: "Monday, April 14, 2025",
    selectTime: "04:00 PM",
    slot: 30,
    type: "upcoming",
    user_role: "user",
  },

  {
    id: 4,
    user_name: "Charlie Brown",
    title: "Client Sync",
    selectDay: "Tuesday, April 15, 2025",
    selectTime: "10:00 AM",
    slot: 60,
    type: "upcoming",
    user_role: "Admin",
  },
  {
    id: 5,
    user_name: "Kevin Spacey",
    title: "Sales Alignment",
    selectDay: "Tuesday, April 15, 2025",
    selectTime: "11:00 AM",
    slot: 30,
    type: "lineup",
    user_role: "Admin",
  },
  {
    id: 6,
    user_name: "Ryan Gosling",
    title: "Demo Prep",
    selectDay: "Tuesday, April 15, 2025",
    selectTime: "12:00 PM",
    slot: 30,
    type: "upcoming",
    user_role: "user",
  },

  {
    id: 16,
    user_name: "Isaac Newton",
    title: "Sprint Review",
    selectDay: "Wednesday, April 16, 2025",
    selectTime: "09:00 AM",
    slot: 30,
    type: "lineup",
    user_role: "Admin",
  },
];

export default fakeAppointments;
