const fakeAppointments = [
  {
    id: 1,
    user_name: "Alice Johnson",
    title: "Project Kickoff",
    selectDay: "Thursday, April 10, 2025",
    selectTime: "10:00 AM",
    slot: 30,
    type: "upcoming",
  },
  {
    id: 2,
    user_name: "Bob Smith",
    title: "Design Review",
    selectDay: "Tuesday, April 08, 2025",
    selectTime: "02:30 PM",
    slot: 30,
    type: "lineup",
  },
  {
    id: 3,
    user_name: "Charlie Brown",
    title: "Client Sync",
    selectDay: "Wednesday, April 09, 2025",
    selectTime: "04:00 PM",
    slot: 30,
    type: "upcoming",
  },
  {
    id: 4,
    user_name: "Dana White",
    title: "Team Retrospective",
    selectDay: "Saturday, April 12, 2025",
    selectTime: "11:00 AM",
    slot: 30,
    type: "lineup",
  },
  {
    id: 5,
    user_name: "Ethan Williams",
    title: "Product Demo",
    selectDay: "Monday, April 14, 2025",
    selectTime: "03:00 PM",
    slot: 30,
    type: "upcoming",
  },
  {
    id: 6,
    user_name: "Fiona Davis",
    title: "Strategy Meeting",
    selectDay: "Sunday, April 13, 2025",
    selectTime: "09:00 AM",
    slot: 30,
    type: "lineup",
  },
  {
    id: 7,
    user_name: "George Miller",
    title: "QA Testing",
    selectDay: "Friday, April 11, 2025",
    selectTime: "01:30 PM",
    slot: 30,
    type: "upcoming",
  },
  {
    id: 8,
    user_name: "Hannah Moore",
    title: "Weekly Planning",
    selectDay: "Thursday, April 17, 2025",
    selectTime: "10:30 AM",
    slot: 30,
    type: "lineup",
  },
  {
    id: 9,
    user_name: "Isaac Newton",
    title: "Sprint Review",
    selectDay: "Friday, April 18, 2025",
    selectTime: "02:00 PM",
    slot: 30,
    type: "upcoming",
  },
  {
    id: 10,
    user_name: "Julia Roberts",
    title: "Innovation Workshop",
    selectDay: "Wednesday, April 16, 2025",
    selectTime: "11:45 AM",
    slot: 30,
    type: "lineup",
  },
];

export default fakeAppointments;
