import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MeetingProvider } from "@/constants/MeetingContext";
import { UserProvider } from "@/constants/UserContext";
import { Toaster } from "react-hot-toast"; // ✅ Import this

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <MeetingProvider>
            {children}
            <Toaster position="top-right" reverseOrder={false} />{" "}
            {/* ✅ Add this */}
          </MeetingProvider>
        </UserProvider>
      </body>
    </html>
  );
}
