import { Inter } from "next/font/google";
import { Fira_Code } from "next/font/google"; // or use JetBrains_Mono
import "./globals.css";
import { MeetingProvider } from "@/constants/MeetingContext";
import { UserProvider } from "@/constants/UserContext";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${firaCode.variable}`}>
      <body>
        <UserProvider>
          <MeetingProvider>
            {children}
            <Toaster position="top-right" reverseOrder={false} />
          </MeetingProvider>
        </UserProvider>
      </body>
    </html>
  );
}
